export const LOAD_CITIES = "LOAD_CITIES";
export const USER_UPDATE_WEATHER_REQUEST = "USER_UPDATE_WEATHER_REQUEST";
export const FETCH_WEATHER = "FETCH_WEATHER";
export const TOGGLE_CONFIG_POPUP = "TOGGLE_CONFIG_POPUP";
export const TEMPERATURE_SCALE_CHANGE = "TEMPERATURE_SCALE_CHANGE";
export const CURRENT_CITY_CHANGE = "CURRENT_CITY_CHANGE";
export const TOGGLE_CITY_MODAL = "TOGGLE_CITY_MODAL";
export const CITY_SEARCH_CHANGE = "CITY_SEARCH_CHANGE";
export const CITY_SEARCH_REQUEST = "CITY_SEARCH_REQUEST";
export const CITY_SEARCH_REQUEST_COMPLETE = "CITY_SEARCH_REQUEST_COMPLETE";
export const CITY_SEARCH_RESET = "CITY_SEARCH_RESET";
export const ADD_CITY = "ADD_CITY";

export const FILTER_WEATHER_COMPLETE = "FILTER_WEATHER_COMPLETE";
export const UPDATE_CITY_WEATHER_REQUEST = "UPDATE_CITY_WEATHER_REQUEST";
export const UPDATE_CITY_WEATHER_COMPLETE = "UPDATE_CITY_WEATHER_COMPLETE";
export const UPDATE_CITY_WEATHER_FAILED = "UPDATE_CITY_WEATHER_FAILED";

export const LOAD_DATA = "LOAD_DATA";
