export const ADD_CITY = "ADD_CITY";
export const LOAD_CITIES = "LOAD_CITIES";
export const USER_UPDATE_WEATHER_REQUEST = "USER_UPDATE_WEATHER_REQUEST";
export const FETCH_WEATHER = "FETCH_WEATHER";
export const TOGGLE_CONFIG_POPUP = "TOGGLE_CONFIG_POPUP";
